export const pagesPopulates: any = {
  thumbnail: { populate: "*" },
  seo: { populate: "*" },
};

export const postsPopulates: any = {
  thumbnail: { populate: "*" },
  categories: { populate: "*" },
  author: { populate: "*" },
  seo: { populate: "*" },
};

export const productsPopulates: any = {
  thumbnail: { populate: "*" },
  seo: { populate: "*" },
};

export const sectionsPopulates: string[] = [
  "container",
  "container.background",
  "container.background.image",
  "container.background.video",
  "container.background.gradient",
  "container.padding.top",
  "container.padding.bottom",
  "container.padding.left",
  "container.padding.right",
  "container.grid",
  "container.grid.rows",
  "container.grid.rows.height",
  "container.grid.rows.padding.top",
  "container.grid.rows.padding.bottom",
  "container.grid.rows.padding.left",
  "container.grid.rows.padding.right",
  "container.grid.rows.columns",
  "container.grid.rows.columns.height",
  "container.grid.rows.columns.innerHeight",
  "container.grid.rows.columns.bottomMargin",
  "container.grid.rows.columns.span",
  "container.grid.rows.columns.padding.top",
  "container.grid.rows.columns.padding.bottom",
  "container.grid.rows.columns.padding.left",
  "container.grid.rows.columns.padding.right",
  "container.grid.rows.columns.alignment",
  "container.grid.rows.columns.background",
  "container.grid.rows.columns.background.image",
  "container.grid.rows.columns.background.video",
  "container.grid.rows.columns.background.gradient",
  "content",
  "content.animation",
  "content.textAlign",
  "content.margin.top",
  "content.margin.bottom",
  "content.margin.left",
  "content.margin.right",
  "content.padding.top",
  "content.padding.bottom",
  "content.padding.left",
  "content.padding.right",
  "content.alignment",
  "content.columnNum",
  "content.files",
  "content.column",
  "content.file",
  "content.url",
  "content.position",
  "content.icon",
  "content.links",
  "content.grid",
  "content.grid.rows",
  "content.grid.rows.columns",
  "content.grid.rows.columns.alignment",
  "content.grid.rows.columns.background",
  "content.grid.rows.columns.spacing",
  "content.width",
  "content.list",
  "content.questions",
  "content.list.alignment",
  "content.list.padding",
  "content.list.padding.top",
  "content.list.padding.bottom",
  "content.list.padding.left",
  "content.list.padding.right",
  "content.list.margin",
  "content.list.position",
  "content.list.text",
  "content.list.text.alignment",
  "content.list.text.padding",
  "content.list.image",
  "content.list.image.file",
  "content.list.image.padding",
  "content.list.image.margin",
  "content.list.background",
  "content.list.background.image",
  "content.list.background.video",
  "content.list.background.gradient",
  "form",
  "form.section",
  "form.fields",
  "form.fields.options",
];

export const propertiesPopulates: string[] = [
  "gallery",
  "agent",
  "fav_users",
  "contacted_users",
];

export const singlePropertyPopulates: string[] = [
  "gallery",
  "seo",
  "seo.icon",
  "agent",
];
