export enum Pages {
  HOME = "home",
  ABOUT = "about-us",
  BLOG = "blog",
  CART = "cart",
  CHECKOUT = "checkout",
  CONTACT = "contact-us",
  GALLERY = "gallery",
  INVOICE = "invoice",
  LOGIN = "login",
  PORTFOLIO = "portfolio",
  REGISTER = "register",
  SERVICES = "services",
  SHOP = "shop",
}
