export enum Pages {
	LOGIN = 'login',
	REGISTER = 'register',
	ACCOUNT = 'account',
	PROJECTS = 'projects',
	CAREERS = 'careers',
	SERVICES = 'services',
	ABOUT_ME = 'about-me',
	CONTACT_ME = 'contact-me',
	BLOG = 'blog',
	SUPPORT = 'support',
	SEARCHED = 'searched',
	PRODUCTS = 'products',
	CART = 'cart',
	CHECKOUT = 'checkout',
	SHOP = 'shop',
	WISHLIST = 'wishlist',
	MENU = 'menu',
	BOOK_TABLE = 'book-table',
	FRAGRANCES = 'fragrances',
	OFFERS = 'offers',
	VIDEOS = 'videos',
	BLOGGERS = 'bloggers',
	TRAINING_ONE = 'training-1',
	TRAINING_TWO = 'training-2'
}
