export enum Resources {
  SOCIAL_LINKS = "social-links",
  FEATURES = "features",
  ACCOUNTS = "accounts",
  USERS = "users",
  MEDIA_LIBRARY = "media-library",
  ATTACHMENTS = "attachments",
  MENUS = "menus",
  MENU_ITEMS = "menu-items",
  PAGES = "pages",
  CATEGORIES = "categories",
  POSTS = "posts",
  TESTIMONIALS = "testimonials",
  MESSAGES = "messages",
  SLIDES = "slides",
  SUBSCRIBERS = "subscribers",
  CUSTOM_CONTENTS = "custom-contents",
  MEMBERS = "members",
  NOTIFICATIONS = "notifications",
  TAGS = "tags",
  COMMENTS = "comments",
  EVENTS = "events",
  USER_GROUPS = "user-groups",
  USER_ROLES = "user-roles",
  POST_TYPES = "post-types",
  MODULES = "modules",
  MODULE_CONTENTS = "module-contents",
}
